name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Installing Browsers and dependencies
      run: pwsh src/bin/Debug/netstandard7.0/playwright.ps1 install --with-deps
    - name: Running tests
      env:
        BROWSER: CHROMIUM
      run: xvfb-run dotnet test ./src/PlaywrightTests.csproj -c Debug -f netcoreapp7.0 --logger:"console;verbosity=detailed" -- Playwright.Retries=1
