name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 test:
    name: ${{ matrix.browser }}/${{ matrix.os }}/.NET 6
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [windows-latest, ubuntu-latest, macos-12]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install prerequisites and download drivers
      shell: bash
      run: ./build.sh --download-driver
    - name: Building
      run: dotnet build ./src
    - name: Installing Browsers and dependencies
      run: pwsh src/PlaywrightDemo/bin/Debug/net7.0/playwright.ps1 install --with-deps
    - name: Running tests
      if: matrix.os != 'ubuntu-latest'
      env:
        BROWSER: ${{ matrix.browser }}
      run: dotnet test ./src/Playwright.Tests/Playwright.Tests.csproj -c Debug -f net6.0 --logger:"console;verbosity=detailed" -- Playwright.Retries=1
    - name: Running tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      env:
        BROWSER: ${{ matrix.browser }}
      run: xvfb-run dotnet test ./src/Playwright.Tests/Playwright.Tests.csproj -c Debug -f net6.0 --logger:"console;verbosity=detailed" -- Playwright.Retries=1
